# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reconmapd < Formula
  desc "Reconmapd: The Reconmap agent allows clients to launch commands remotely, open interactive browser terminals, and receive push notifications."
  homepage "https://github.com/reconmap/agent"
  version "0.9.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.9/reconmapd-darwin-amd64.tar.gz"
      sha256 "21191cd6b0e9c70d4ad13b9fd632e895bb6abe39b811de56c3713be2a1e416cb"

      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.9/reconmapd-darwin-arm64.tar.gz"
      sha256 "34c4460a707de087a90a2ad857ae23f5a485732d5fa7b8c3f7e8ea5c82a4e392"

      def install
        bin.install "reconmapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.9/reconmapd-linux-amd64.tar.gz"
      sha256 "c261b2d8065925bad48a639cf72b6c35ca5249ad93d9268c16b3cbdfc0131cc2"
      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.9/reconmapd-linux-arm.tar.gz"
      sha256 "05a1c3192ea464af13252896a553441dd9bd7381b7a4a5f16dc3aced7304de54"
      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.9/reconmapd-linux-arm64.tar.gz"
      sha256 "6486a5cd1ac12c36e024c13a3e57c676a0e8037aefbccdc8f2da5161704500cb"
      def install
        bin.install "reconmapd"
      end
    end
  end
end
