# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReconmapCli < Formula
  desc "Reconmap tools as homebrew tap."
  homepage "https://github.com/reconmap"
  version "0.9.7"
  license "GPL3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.7/reconmap-cli-Darwin-x86_64.tar.gz"
      sha256 "740974f563e4bb71704b647bbe7009248dafbf5c1850dc1da1969aeb94bac37b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.7/reconmap-cli-Linux-x86_64.tar.gz"
      sha256 "a62bbae0a21715b157be1d8c022b6dd0173ea41541632b04a6d31141c568d078"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/cli/releases/download/0.9.7/reconmap-cli-Linux-arm64.tar.gz"
      sha256 "97446eab95983f60d7711c92faf93fc23ffb51fb51a440b5db40a7f46489fe0d"
    end
  end

  def install
    bin.install "reconmap-cli"
  end
end
