# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reconmapd < Formula
  desc "Reconmapd: The Reconmap agent allows clients to launch commands remotely, open interactive browser terminals, and receive push notifications."
  homepage "https://github.com/reconmap/agent"
  version "0.8.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.8.7/reconmapd-Darwin-x86_64.tar.gz"
      sha256 "c5cf5f8c8b6bff04d91275dca84fb44e19547e282054e9da76ba99166c0d505f"

      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.8.7/reconmapd-Darwin-arm64.tar.gz"
      sha256 "d2114ba3a286d5194635176b120d78601627a502e8997d3f5d4c115f5836f575"

      def install
        bin.install "reconmapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.8.7/reconmapd-Linux-arm.tar.gz"
      sha256 "1a4810a1e07aeccc48be108b052997c70e809d0cb340ff64df8c53c861e3a02b"

      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.8.7/reconmapd-Linux-x86_64.tar.gz"
      sha256 "65634125b9186523c22648f188a237911d4ef915c0ff9a1cf0e50cfcfa00d362"

      def install
        bin.install "reconmapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/command-line-tools/releases/download/0.8.7/reconmapd-Linux-arm64.tar.gz"
      sha256 "03d214d31982a1c9709119c8c0e9338c65df1366a821d4981540035fb74c9e2b"

      def install
        bin.install "reconmapd"
      end
    end
  end
end
