# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmap < Formula
  desc "Reconmap tools as homebrew tap."
  homepage "https://github.com/reconmap"
  version "0.9.15"
  license "GPL-3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.15/rmap-Darwin-x86_64.tar.gz"
      sha256 "73810a8ecc1d319d9b5086a81a417653256c10adadf7298ef08af618daac69a9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/reconmap/cli/releases/download/0.9.15/rmap-Darwin-arm64.tar.gz"
      sha256 "5a659589a63d9378dea885ae573e054eb8602b5b1bb4ab3f4a5eadc1633d4127"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.15/rmap-Linux-x86_64.tar.gz"
      sha256 "ccefa5e7461fe92fd2d0e5de94a73e4900c3ccb6c327dea7f098083de0735030"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/cli/releases/download/0.9.15/rmap-Linux-arm.tar.gz"
      sha256 "d67d661c9c5b5c4e81f179010304246533f40098f4857d849f32d12b4061706c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/cli/releases/download/0.9.15/rmap-Linux-arm64.tar.gz"
      sha256 "b14425f6ba9f31e089d72e8a2c2978d4ff11607de3cbc9243909e8245cd887a7"
    end
  end

  def install
    bin.install "rmap"
  end
end
