# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rmap < Formula
  desc "Rmap: Command line interface for the Reconmap pentest automation and reporting tool."
  homepage "https://github.com/reconmap/cli"
  version "0.9.16"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reconmap/cli/releases/download/0.9.16/rmap-Darwin-arm64.tar.gz"
      sha256 "e3751dca7b33f380912f1300273113c816fd9918a77c90cb29b874bd6af35b55"

      def install
        bin.install "rmap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.16/rmap-Darwin-x86_64.tar.gz"
      sha256 "ff54b23ee3cf20e841b5e443d45a97b2aff7fe60635bef459e8647842741185f"

      def install
        bin.install "rmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/cli/releases/download/0.9.16/rmap-Linux-arm.tar.gz"
      sha256 "3ff7ddc0a6c634261f049dda983741ff037a30179f454304f1b16fdc1d76918a"

      def install
        bin.install "rmap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reconmap/cli/releases/download/0.9.16/rmap-Linux-x86_64.tar.gz"
      sha256 "0f0d9f8eb05ca67a6fa9ec5963883da5fd41a8e8fa90fe204fe1501a2b21feab"

      def install
        bin.install "rmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reconmap/cli/releases/download/0.9.16/rmap-Linux-arm64.tar.gz"
      sha256 "25a5b6c868aefd66a0747f22efe11ff339a1157c2af39c9469e760cea0f2b6ad"

      def install
        bin.install "rmap"
      end
    end
  end
end
