# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmap" do
  desc "Rmap: Command line interface for the Reconmap pentest automation and reporting tool."
  homepage "https://github.com/reconmap/command-line-tools/tree/main/cli"
  version "0.9.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rmap"

  on_macos do
    on_intel do
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.24/rmap-darwin-amd64.tar.gz"
      sha256 "0abb24c0b2f37bb758d36be63c64be80d61be92fdef146f28f842166ef8a869f"
    end
    on_arm do
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.24/rmap-darwin-arm64.tar.gz"
      sha256 "4ed0204ac177bf6ad5929a7eb6445bd70f5c1c4793659117245d1cb9ffd6fec3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.24/rmap-linux-amd64.tar.gz"
      sha256 "7d69acc8e7fc1bc2bf3359487cc62ee090b504b216ccbe085e1148d82bff92bb"
    end
    on_arm do
      url "https://github.com/reconmap/command-line-tools/releases/download/0.9.24/rmap-linux-arm64.tar.gz"
      sha256 "2a4c5da606831a3faeadc5b1e4bc247a94eb643ba779bc357633d9e740283ce3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rmap"]
    end
  end

  # No zap stanza required
end
